# fly.toml app configuration file generated for green-shape-2878 on 2023-07-13T16:02:02+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-shape-2878"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
